### ISSUE TITLE
Great design

### ISSUE THREAD

**Issue by diegosaul402** [Galuz/ProfilePage#1]
In general your page have a great design, simple and clean, I like it. 
But I can see your page still has a lot "Lorem ipsum" text, so there is really low content about you.

Something I notice is you do just 2 commits on git, that doesn't help up to understand how do you do your work or how your progress was. I recomend you to use git more for your projects, it really helps.
Anyways, your code looks very good, super easy to read it. Greetings

**Comment by Galuz** [comment]
Lorem impsu is aready fixed, and now i used git for all changes with the second project
