### ISSUE TITLE
Bootstrap classes

### ISSUE THREAD

**Issue by tzohpilotl** [Galuz/ProfilePage#2]
Hello, Germán. I just looked at your page and really liked the effort you put by creating a lot of the classes you used to style your page. On the other hand, I would recommend to use Bootstrap classes to create a preliminary design and then go from there, you will find this a lot more easier. I hope to see more of your work in the future!

**Comment by Galuz** [comment]
Okay, that's because I don't know very well how to use bootstrap, but in this weekend I will take a course, to learn all bootstrap tricks.
Thx and regards
