### ISSUE TITLE
Lorem ipsum

### ISSUE THREAD

**Issue by salvadorJimenez** [Galuz/ProfilePage#8]
Well like the title say, the lorep ipsum don't describe really good your experience in IOS and ORACLE PLSQL.

So if you can put the correct information would be great.

Another thing is the nav-bar,  maybe you should fixed to the top, becouse for me is annoying that when i click in some element of the nav bar ok is good that scroll-me to the view but the nav-bar dissapear.

The responsive design doesnt work in the navbar and the profesional skills. So if you can fixed would be nice.

You can use a better fonts and maybe make it with more styles.

The footer is good but for me is too big maybe you can change the heigth of the footer. 

Thats it Galuz. I know that maybe you have a lot of work, but don't take my comments like a bad thing, I'm not the best web developer but this is my opinion. So see you around.

**Comment by Galuz** [comment]
done i already add your recomendations, thx
